name: Render and Publish

on:
  push:
    branches: ["main"]
    paths-ignore:
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .gitlab-ci.yml
      - LICENSE
      - README.md

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: hogg2010.qmd
          sparse-checkout-cone-mode: false
      - uses: julia-actions/setup-julia@v1
      - name: install dependencies and iosevka fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y librsvg2-bin
          julia --project=. -e 'using Pkg; Pkg.add(["Turing", "StatsPlots", "LogExpFunctions", "KernelDensity"])'
          mkdir /tmp/iosevka
          RELEASE="33.2.2"
          wget -P /tmp/iosevka https://github.com/be5invis/Iosevka/releases/download/v$RELEASE/PkgTTC-Iosevka-$RELEASE.zip
          unzip /tmp/iosevka/*.zip -d /tmp/iosevka
          sudo mv /tmp/iosevka/*.ttc /usr/local/share/fonts/
          sudo fc-cache -fv
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
      - uses: quarto-dev/quarto-actions/render@v2
        with:
          path: hogg2010.qmd
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
